# Generated by Django 5.2.9 on 2026-01-13 18:02

import apps.common.utils.files.files
import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_add_trgm_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='post_title_trgm_gin',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_shdesc_trgm_gin',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_text_trgm_gin',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_slug_trgm_gin',
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=core.storages.PublicMediaStorage(), upload_to=apps.common.utils.files.files.unique_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(storage=core.storages.PublicMediaStorage(), upload_to=apps.common.utils.files.files.unique_image_path),
        ),
    ]
