# Generated by Django 5.2.9 on 2026-01-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_post_title_trgm_gin_post_post_shdesc_trgm_gin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views_count',
            new_name='views_count_total',
        ),
        migrations.AddField(
            model_name='post',
            name='views_count_unique',
            field=models.BigIntegerField(default=0),
        ),
    ]
