# Generated by Django 5.2.10 on 2026-07-31 19:14

import apps.common.utils.files.files
import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0015_rename_views_count_post_views_count_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=core.storages.select_storage,
                upload_to=apps.common.utils.files.files.unique_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=models.ImageField(
                storage=core.storages.select_storage,
                upload_to=apps.common.utils.files.files.unique_image_path,
            ),
        ),
    ]
